# Generated by Django 2.2.12 on 2020-04-15 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='file',
            field=models.FileField(upload_to='files/'),
        ),
        migrations.AlterField(
            model_name='certification',
            name='image',
            field=models.ImageField(upload_to='files/'),
        ),
        migrations.AlterField(
            model_name='certification',
            name='pdf',
            field=models.FileField(upload_to='files/'),
        ),
    ]
